# Configure the dependency superbuild and download its sources without compiling.
# The first build completes the dependency superbuild, then CMake regenerates the
# parent project and continues with the native OrcaSlicer targets.

option(BUILD_DEPS_ONLY "Configure and build only the dependency superbuild" OFF)
option(BUILD_SLICER_ONLY "Configure and build only OrcaSlicer using an external prefix" OFF)

if (BUILD_DEPS_ONLY AND BUILD_SLICER_ONLY)
    message(FATAL_ERROR "BUILD_DEPS_ONLY and BUILD_SLICER_ONLY cannot both be ON")
endif ()

set(_orca_explicit_prefix FALSE)
if (NOT "${CMAKE_PREFIX_PATH}" STREQUAL ""
        AND NOT "${CMAKE_PREFIX_PATH}" STREQUAL "${AUTOGENERATED_PREFIX_PATH}")
    set(_orca_explicit_prefix TRUE)
endif ()

if (BUILD_DEPS_ONLY AND _orca_explicit_prefix)
    message(FATAL_ERROR "BUILD_DEPS_ONLY cannot be used with an explicit CMAKE_PREFIX_PATH")
endif ()

if (BUILD_SLICER_ONLY)
    if ("${CMAKE_PREFIX_PATH}" STREQUAL "")
        message(FATAL_ERROR "BUILD_SLICER_ONLY requires CMAKE_PREFIX_PATH")
    endif ()
    set(ORCA_AUTO_DEPS_ENABLED FALSE)
    return ()
endif ()

set(DEPS_C_FLAGS "" CACHE STRING "Extra C compiler flags applied to all dependencies")
set(DEPS_CXX_FLAGS "" CACHE STRING "Extra C++ compiler flags applied to all dependencies")
set(DEPS_LINKER_FLAGS "" CACHE STRING "Extra linker flags applied to all dependencies")
set(ORCA_DEPS_BUILD_JOBS "" CACHE STRING "Maximum parallel jobs used inside dependency builds")
set(_orca_deps_build_jobs "${ORCA_DEPS_BUILD_JOBS}")
if ("${_orca_deps_build_jobs}" STREQUAL "" AND DEFINED ENV{ORCA_DEPS_BUILD_JOBS}
        AND NOT "$ENV{ORCA_DEPS_BUILD_JOBS}" STREQUAL "")
    set(_orca_deps_build_jobs "$ENV{ORCA_DEPS_BUILD_JOBS}")
endif ()
if ("${_orca_deps_build_jobs}" STREQUAL "")
    set(_orca_deps_build_jobs 1)
endif ()
if (NOT "${_orca_deps_build_jobs}" MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "ORCA_DEPS_BUILD_JOBS must be a positive integer")
endif ()
set(ORCA_DEPS_BUILD_JOBS "${_orca_deps_build_jobs}" CACHE STRING "Maximum parallel jobs used inside dependency builds" FORCE)

set(ORCA_AUTO_DEPS_ENABLED TRUE)
set(DEP_BUILD_DIR "${CMAKE_BINARY_DIR}/deps" CACHE PATH "Path to the dependency superbuild" FORCE)
set(_orca_dep_prefix "${DEP_BUILD_DIR}/OrcaSlicer_dep/usr/local")
set(CMAKE_PREFIX_PATH "${_orca_dep_prefix}" CACHE PATH "Path to dependencies install directory" FORCE)
set(AUTOGENERATED_PREFIX_PATH "${CMAKE_PREFIX_PATH}" CACHE STRING "Provides the last autogenerated CMAKE_PREFIX_PATH" FORCE)

set(DEP_DOWNLOAD_DIR "${CMAKE_SOURCE_DIR}/deps/DL_CACHE" CACHE PATH "Path for downloaded source packages")
set(_orca_deps_configure_args
    -S "${CMAKE_SOURCE_DIR}/deps"
    -B "${DEP_BUILD_DIR}"
    -G "${CMAKE_GENERATOR}"
    "-DDEPS_C_FLAGS=${DEPS_C_FLAGS}"
    "-DDEPS_CXX_FLAGS=${DEPS_CXX_FLAGS}"
    "-DDEPS_LINKER_FLAGS=${DEPS_LINKER_FLAGS}"
    "-DDEPS_BUILD_JOBS=${_orca_deps_build_jobs}"
)
if (CMAKE_GENERATOR_PLATFORM)
    list(APPEND _orca_deps_configure_args -A "${CMAKE_GENERATOR_PLATFORM}")
endif ()
foreach (_orca_var CMAKE_BUILD_TYPE CMAKE_MAKE_PROGRAM CMAKE_C_COMPILER CMAKE_CXX_COMPILER
                   CMAKE_C_COMPILER_LAUNCHER CMAKE_CXX_COMPILER_LAUNCHER CMAKE_TOOLCHAIN_FILE)
    if (NOT "${${_orca_var}}" STREQUAL "")
        list(APPEND _orca_deps_configure_args "-D${_orca_var}=${${_orca_var}}")
    endif ()
endforeach ()

set(_orca_deps_build_command ${CMAKE_COMMAND} --build)
if (WIN32 AND MSVC)
    set(_orca_sdk_root "$ENV{ProgramFiles\(x86\)}/Windows Kits/10")
    file(GLOB _orca_sdk_rc LIST_DIRECTORIES false "${_orca_sdk_root}/bin/*/x64/rc.exe")
    list(SORT _orca_sdk_rc COMPARE NATURAL ORDER DESCENDING)
    list(GET _orca_sdk_rc 0 _orca_sdk_rc)
    get_filename_component(_orca_rc_dir "${_orca_sdk_rc}" DIRECTORY)
    get_filename_component(_orca_llvm_bin "${CMAKE_CXX_COMPILER}" DIRECTORY)
    get_filename_component(_orca_vc_root "${_orca_llvm_bin}/../../../.." ABSOLUTE)
    file(GLOB _orca_msvc_bin LIST_DIRECTORIES true "${_orca_vc_root}/Tools/MSVC/*/bin/Hostx64/x64")
    if (_orca_msvc_bin)
        list(SORT _orca_msvc_bin COMPARE NATURAL ORDER DESCENDING)
        list(GET _orca_msvc_bin 0 _orca_msvc_bin)
        file(REAL_PATH "${_orca_msvc_bin}/../../.." _orca_msvc_root)
        get_filename_component(_orca_sdk_version_dir "${_orca_rc_dir}" DIRECTORY)
        get_filename_component(_orca_sdk_version "${_orca_sdk_version_dir}" NAME)
        set(_orca_deps_build_path "${_orca_msvc_bin};${_orca_rc_dir};$ENV{PATH}")
        set(_orca_deps_build_include
            "${_orca_msvc_root}/include;${_orca_sdk_root}/Include/${_orca_sdk_version}/shared;${_orca_sdk_root}/Include/${_orca_sdk_version}/um;${_orca_sdk_root}/Include/${_orca_sdk_version}/ucrt;${_orca_sdk_root}/Include/${_orca_sdk_version}/winrt")
        set(_orca_deps_build_lib
            "${_orca_msvc_root}/lib/x64;${_orca_sdk_root}/Lib/${_orca_sdk_version}/um/x64;${_orca_sdk_root}/Lib/${_orca_sdk_version}/ucrt/x64")
        string(REPLACE ";" "\\;" _orca_deps_build_path "${_orca_deps_build_path}")
        string(REPLACE ";" "\\;" _orca_deps_build_include "${_orca_deps_build_include}")
        string(REPLACE ";" "\\;" _orca_deps_build_lib "${_orca_deps_build_lib}")
        set(_orca_deps_build_command
            ${CMAKE_COMMAND} -E env
            "PATH=${_orca_deps_build_path}"
            "INCLUDE=${_orca_deps_build_include}"
            "LIB=${_orca_deps_build_lib}"
            ${CMAKE_COMMAND} --build)
    endif ()
endif ()

if (EXISTS "${DEP_BUILD_DIR}/CMakeCache.txt")
    file(STRINGS "${DEP_BUILD_DIR}/CMakeCache.txt" _orca_old_generator REGEX "^CMAKE_GENERATOR:INTERNAL=")
    if (NOT "${_orca_old_generator}" STREQUAL "CMAKE_GENERATOR:INTERNAL=${CMAKE_GENERATOR}")
        file(REMOVE "${DEP_BUILD_DIR}/CMakeCache.txt")
        file(REMOVE_RECURSE "${DEP_BUILD_DIR}/CMakeFiles")
    endif ()
endif ()

execute_process(
    COMMAND ${CMAKE_COMMAND} ${_orca_deps_configure_args}
    RESULT_VARIABLE _orca_deps_configure_result
)
if (NOT _orca_deps_configure_result EQUAL 0)
    message(FATAL_ERROR "Dependency superbuild configure failed")
endif ()

execute_process(
    COMMAND ${_orca_deps_build_command} "${DEP_BUILD_DIR}" --target deps_download
    RESULT_VARIABLE _orca_deps_download_result
)
if (NOT _orca_deps_download_result EQUAL 0)
    message(FATAL_ERROR "Dependency download or patch stage failed")
endif ()

set(_orca_deps_stamp "${DEP_BUILD_DIR}/.orca_deps_complete.stamp")
set(_orca_deps_stamp_script "${CMAKE_SOURCE_DIR}/cmake/modules/OrcaAutoBuildDepsStamp.cmake")

if (NOT EXISTS "${_orca_deps_stamp}")
    execute_process(
        COMMAND ${CMAKE_COMMAND}
            -DORCA_DEPS_ACCEPT_EXISTING=ON
            "-DORCA_DEPS_STAMP=${_orca_deps_stamp}"
            "-DORCA_DEPS_SOURCE_DIR=${CMAKE_SOURCE_DIR}/deps"
            "-DORCA_DEPS_BUILD_DIR=${DEP_BUILD_DIR}"
            -P "${_orca_deps_stamp_script}"
        RESULT_VARIABLE _orca_existing_stamp_result
    )
    if (NOT _orca_existing_stamp_result EQUAL 0)
        message(FATAL_ERROR "Could not validate the existing dependency tree")
    endif ()
endif ()

if (BUILD_DEPS_ONLY)
    set(_orca_deps_bootstrap TRUE)
elseif (EXISTS "${_orca_deps_stamp}")
    set(_orca_deps_bootstrap FALSE)
else ()
    set(_orca_deps_bootstrap TRUE)
endif ()

set(ORCA_AUTO_DEPS_TARGET deps)
if (WIN32)
    set(ORCA_AUTO_DEPS_APP_TARGET OrcaSlicer_app_gui)
else ()
    set(ORCA_AUTO_DEPS_APP_TARGET OrcaSlicer)
endif ()
if (_orca_deps_bootstrap AND NOT BUILD_DEPS_ONLY)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_orca_deps_stamp}")
    add_custom_command(
        OUTPUT "${_orca_deps_stamp}"
        COMMAND ${CMAKE_COMMAND} -DORCA_DEPS_PREPARE=ON
                "-DORCA_DEPS_STAMP=${_orca_deps_stamp}"
                "-DORCA_DEPS_SOURCE_DIR=${CMAKE_SOURCE_DIR}/deps"
                "-DORCA_DEPS_BUILD_DIR=${DEP_BUILD_DIR}"
                -P "${_orca_deps_stamp_script}"
        COMMAND ${_orca_deps_build_command} "${DEP_BUILD_DIR}" --target deps --config "$<CONFIG>" --parallel 1
        COMMAND ${CMAKE_COMMAND} "-DORCA_DEPS_STAMP=${_orca_deps_stamp}"
                "-DORCA_DEPS_SOURCE_DIR=${CMAKE_SOURCE_DIR}/deps"
                "-DORCA_DEPS_BUILD_DIR=${DEP_BUILD_DIR}"
                -P "${_orca_deps_stamp_script}"
        COMMAND ${CMAKE_COMMAND} -S "${CMAKE_SOURCE_DIR}" -B "${CMAKE_BINARY_DIR}"
        DEPENDS "${DEP_BUILD_DIR}/CMakeCache.txt"
        USES_TERMINAL
        VERBATIM
    )
    add_custom_target(deps DEPENDS "${_orca_deps_stamp}")
else ()
    add_custom_target(deps
        COMMAND ${CMAKE_COMMAND} -DORCA_DEPS_PREPARE=ON
                "-DORCA_DEPS_STAMP=${_orca_deps_stamp}"
                "-DORCA_DEPS_SOURCE_DIR=${CMAKE_SOURCE_DIR}/deps"
                "-DORCA_DEPS_BUILD_DIR=${DEP_BUILD_DIR}"
                -P "${_orca_deps_stamp_script}"
        COMMAND ${_orca_deps_build_command} "${DEP_BUILD_DIR}" --target deps --config "$<CONFIG>" --parallel 1
        COMMAND ${CMAKE_COMMAND} "-DORCA_DEPS_STAMP=${_orca_deps_stamp}"
                "-DORCA_DEPS_SOURCE_DIR=${CMAKE_SOURCE_DIR}/deps"
                "-DORCA_DEPS_BUILD_DIR=${DEP_BUILD_DIR}"
                -P "${_orca_deps_stamp_script}"
        USES_TERMINAL
        VERBATIM
    )
endif ()


if (_orca_deps_bootstrap)
    if (BUILD_DEPS_ONLY)
        add_custom_target(orca_deps_default ALL DEPENDS deps)
    else ()
        add_custom_target(${ORCA_AUTO_DEPS_APP_TARGET} ALL DEPENDS deps)
    endif ()
    message(STATUS "Dependencies were downloaded, updated, and patched. The first build will configure, compile, and install them before regenerating OrcaSlicer targets.")
    set(ORCA_AUTO_DEPS_BOOTSTRAP TRUE)
else ()
    set(ORCA_AUTO_DEPS_BOOTSTRAP FALSE)
endif ()
