if (NOT DEFINED ORCA_DEPS_SOURCE_DIR OR NOT DEFINED ORCA_DEPS_STAMP
        OR NOT DEFINED ORCA_DEPS_BUILD_DIR)
    message(FATAL_ERROR "ORCA_DEPS_SOURCE_DIR, ORCA_DEPS_STAMP and ORCA_DEPS_BUILD_DIR are required")
endif ()

set(_orca_manifest "${ORCA_DEPS_BUILD_DIR}/orca-deps-manifest.cmake")
if (NOT EXISTS "${_orca_manifest}")
    message(FATAL_ERROR "Dependency manifest is missing: ${_orca_manifest}")
endif ()
include("${_orca_manifest}")

function(_orca_project_hash project output)
    set(_files "${ORCA_DEPS_SOURCE_DIR}/CMakeLists.txt")
    file(GLOB _project_files
        "${ORCA_DEPS_SOURCE_DIR}/${project}/*.cmake"
        "${ORCA_DEPS_SOURCE_DIR}/${project}/*.patch"
    )
    list(APPEND _files ${_project_files})
    list(SORT _files)
    set(_digest "")
    foreach (_file IN LISTS _files)
    endforeach ()
    string(MD5 _hash "${_digest}")
    set(${output} "${_hash}" PARENT_SCOPE)
endfunction()

set(_orca_hash_manifest "${ORCA_DEPS_BUILD_DIR}/.orca_deps_recipe_hashes.cmake")
set(_orca_changed)
if (EXISTS "${_orca_hash_manifest}")
    include("${_orca_hash_manifest}")
endif ()
foreach (_project IN LISTS ORCA_DEPS_PROJECTS)
    _orca_project_hash("${_project}" _current_hash)
    if (NOT "${ORCA_DEPS_HASH_${_project}}" STREQUAL "${_current_hash}")
        list(APPEND _orca_changed "${_project}")
    endif ()
    set(_orca_current_hash_${_project} "${_current_hash}")
endforeach ()

if (ORCA_DEPS_PREPARE AND NOT EXISTS "${_orca_hash_manifest}")
    return ()
endif ()

if (ORCA_DEPS_PREPARE)
    set(_orca_invalidated ${_orca_changed})
    set(_orca_grew TRUE)
    while (_orca_grew)
        set(_orca_grew FALSE)
        foreach (_project IN LISTS ORCA_DEPS_PROJECTS)
            if (_project IN_LIST _orca_invalidated)
                continue ()
            endif ()
            foreach (_dependency IN LISTS ORCA_DEPS_DEPENDS_${_project})
                string(REGEX REPLACE "^dep_" "" _dependency_name "${_dependency}")
                if (_dependency_name IN_LIST _orca_invalidated)
                    list(APPEND _orca_invalidated "${_project}")
                    set(_orca_grew TRUE)
                    break ()
                endif ()
            endforeach ()
        endforeach ()
    endwhile ()
    list(REMOVE_DUPLICATES _orca_invalidated)
    foreach (_project IN LISTS _orca_invalidated)
        set(_project_prefix "${ORCA_DEPS_BUILD_DIR}/dep_${_project}-prefix/src")
        file(REMOVE_RECURSE
            "${_project_prefix}/dep_${_project}"
            "${_project_prefix}/dep_${_project}-build"
        )
        foreach (_step mkdir download update patch configure build install done)
            file(REMOVE "${_project_prefix}/dep_${_project}-stamp/dep_${_project}-${_step}")
        endforeach ()
        file(REMOVE
            "${_project_prefix}/dep_${_project}-stamp/dep_${_project}-gitclone-lastrun.txt"
        )
    endforeach ()
    if (_orca_invalidated)
        message(STATUS "Invalidated dependency projects: ${_orca_invalidated}")
    endif ()
    foreach (_project IN LISTS ORCA_DEPS_PROJECTS)
        file(APPEND "${_orca_hash_manifest}" "set(ORCA_DEPS_HASH_${_project} \"${_orca_current_hash_${_project}}\")\n")
    endforeach ()
    return ()
endif ()

if (ORCA_DEPS_ACCEPT_EXISTING AND NOT EXISTS "${ORCA_DEPS_STAMP}")
    set(_orca_complete TRUE)
    foreach (_project IN LISTS ORCA_DEPS_PROJECTS)
        if (NOT EXISTS "${ORCA_DEPS_BUILD_DIR}/dep_${_project}-prefix/src/dep_${_project}-stamp/dep_${_project}-install")
            set(_orca_complete FALSE)
            break ()
        endif ()
    endforeach ()
    if (NOT _orca_complete)
        return ()
    endif ()
endif ()

file(WRITE "${_orca_hash_manifest}" "")
set(_all_hashes "")
foreach (_project IN LISTS ORCA_DEPS_PROJECTS)
    file(APPEND "${_orca_hash_manifest}" "set(ORCA_DEPS_HASH_${_project} \"${_orca_current_hash_${_project}}\")\n")
    string(APPEND _all_hashes "${_orca_current_hash_${_project}}")
endforeach ()
string(MD5 _orca_recipe_hash "${_all_hashes}")
file(WRITE "${ORCA_DEPS_STAMP}" "${_orca_recipe_hash}\n")
