# BuildHookExamples.cmake - invoked via cmake -P to build 4 examples against freshly generated SDK
# Called from orca_hook_examples target after OrcaSlicer post-link generation.
# Reads build_id from generated report, never from hardcoded values.

# In script mode (cmake -P) CMake overwrites CMAKE_SOURCE_DIR/CMAKE_BINARY_DIR with the working
# directory, so the caller passes ORCA_SOURCE_DIR/ORCA_BINARY_DIR instead.
if(NOT DEFINED ORCA_SOURCE_DIR)
  message(FATAL_ERROR "ORCA_SOURCE_DIR must be passed with -D")
endif()
if(NOT DEFINED ORCA_BINARY_DIR)
  message(FATAL_ERROR "ORCA_BINARY_DIR must be passed with -D")
endif()
set(CMAKE_SOURCE_DIR "${ORCA_SOURCE_DIR}")
set(CMAKE_BINARY_DIR "${ORCA_BINARY_DIR}")
set(REPORT_JSON "${CMAKE_BINARY_DIR}/generated/hook-sdkgen/report/hook-sdkgen-report.json")
if(NOT EXISTS "${REPORT_JSON}")
  message(FATAL_ERROR "Hook SDK report not found at ${REPORT_JSON} - ensure OrcaSlicer post-link generation ran")
endif()

file(READ "${REPORT_JSON}" _report_json)
string(JSON BUILD_ID GET "${_report_json}" build build_id)
if(NOT BUILD_ID)
  message(FATAL_ERROR "Could not parse build_id from ${REPORT_JSON}")
endif()
message(STATUS "Building hook examples for build_id: ${BUILD_ID}")

set(SDK_ROOT "${CMAKE_BINARY_DIR}/generated/plugin-sdk/${BUILD_ID}")
if(NOT EXISTS "${SDK_ROOT}")
  message(FATAL_ERROR "SDK root not found: ${SDK_ROOT}")
endif()

function(update_file_build_id file_path)
  if(NOT EXISTS "${file_path}")
    return()
  endif()
  file(READ "${file_path}" _content)
  string(REGEX REPLACE "windows-x86_64-[a-z0-9\\-]+" "${BUILD_ID}" _new_content "${_content}")
  if(NOT "${_content}" STREQUAL "${_new_content}")
    file(WRITE "${file_path}" "${_new_content}")
    message(STATUS "Updated ${file_path} to build_id ${BUILD_ID}")
  endif()
endfunction()

update_file_build_id("${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/rust/Cargo.toml")
update_file_build_id("${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/java/build.gradle.kts")
update_file_build_id("${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/kotlin/build.gradle.kts")
update_file_build_id("${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/java/src/main/resources/META-INF/orca/plugin.json")
update_file_build_id("${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/kotlin/src/main/resources/META-INF/orca/plugin.json")

# Stable "latest" copy so a manual cargo/gradle invocation can find the SDK without the build id.
set(LATEST_SDK "${CMAKE_BINARY_DIR}/generated/plugin-sdk/latest")
execute_process(COMMAND ${CMAKE_COMMAND} -E rm -rf "${LATEST_SDK}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory "${SDK_ROOT}" "${LATEST_SDK}")
message(STATUS "Building C++ example...")
set(CPP_BUILD_DIR "${CMAKE_BINARY_DIR}/hook-examples/cpp")
if(WIN32)
  # Clean previous CMakeCache if generator mismatch (CLion may have used Visual Studio)
  file(REMOVE "${CPP_BUILD_DIR}/CMakeCache.txt")
  file(REMOVE_RECURSE "${CPP_BUILD_DIR}/CMakeFiles")
  # `call vcvars64.bat` resets ERRORLEVEL, so each step must propagate its own exit code,
  # otherwise a failed configure looks successful and the build step fails with a confusing message.
  file(WRITE "${CMAKE_BINARY_DIR}/build_cpp_configure.bat" "call \"C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" >nul\r\ncmake -S \"${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/cpp\" -B \"${CPP_BUILD_DIR}\" -G Ninja -DCMAKE_C_COMPILER=\"C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe\" -DCMAKE_CXX_COMPILER=\"C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe\" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DORCA_SDK_DIR=\"${SDK_ROOT}/cpp\"\r\nif errorlevel 1 exit /b 1\r\n")
  execute_process(COMMAND cmd /c "${CMAKE_BINARY_DIR}/build_cpp_configure.bat" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "C++ example configure failed: ${_out} ${_err}")
  endif()
  file(WRITE "${CMAKE_BINARY_DIR}/build_cpp_build.bat" "call \"C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" >nul\r\ncmake --build \"${CPP_BUILD_DIR}\" --parallel 8\r\n")
  execute_process(COMMAND cmd /c "${CMAKE_BINARY_DIR}/build_cpp_build.bat" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "C++ example build failed: ${_out} ${_err}")
  endif()
else()
  execute_process(COMMAND ${CMAKE_COMMAND} -S "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/cpp" -B "${CPP_BUILD_DIR}" -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DORCA_SDK_DIR=${SDK_ROOT}/cpp RESULT_VARIABLE _res)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "C++ configure failed")
  endif()
  execute_process(COMMAND ${CMAKE_COMMAND} --build "${CPP_BUILD_DIR}" --parallel 8 RESULT_VARIABLE _res)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "C++ build failed")
  endif()
endif()
message(STATUS "C++ example built: ${CPP_BUILD_DIR}/orca_cpp_example.dll")

# Build Rust example (uses ORCA_BUILD_ID env)
message(STATUS "Building Rust example...")
if(WIN32)
  file(WRITE "${CMAKE_BINARY_DIR}/build_rust.bat" "call \"C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" >nul\r\nset ORCA_BUILD_ID=${BUILD_ID}\r\ncargo build --manifest-path \"${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/rust/Cargo.toml\" --release\r\n")
  execute_process(COMMAND cmd /c "${CMAKE_BINARY_DIR}/build_rust.bat" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "Rust build failed: ${_out} ${_err}")
  endif()
else()
  execute_process(COMMAND cargo build --manifest-path "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/rust/Cargo.toml" --release RESULT_VARIABLE _res)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "Rust build failed")
  endif()
endif()
message(STATUS "Rust example built")

# Build Java example (javac + jar, using SDK's build_id via report, with annotation processor)
message(STATUS "Building Java example...")
set(JAVA_HOME "C:/Program Files/Eclipse Adoptium/jdk-25.0.3.9-hotspot")
set(JAVAC "${JAVA_HOME}/bin/javac.exe")
set(JAR "${JAVA_HOME}/bin/jar.exe")
set(JAVA_SDK "${SDK_ROOT}/jvm")
# Build artifacts belong in the build tree, never inside the source tree: writing the jar under
# sdk/ pollutes the checkout and a stale handle on it blocks every later build.
set(JAVA_BUILD_DIR "${CMAKE_BINARY_DIR}/hook-examples/java")
file(MAKE_DIRECTORY "${JAVA_BUILD_DIR}/classes")
file(MAKE_DIRECTORY "${JAVA_BUILD_DIR}/libs")
set(JAVA_GEN_DIR "${CMAKE_BINARY_DIR}/java-gen")
file(MAKE_DIRECTORY "${JAVA_GEN_DIR}")
# 1) compile processor alone so it can be discovered
file(GLOB_RECURSE _proc_sources "${JAVA_SDK}/src/main/java/org/orcaslicer/plugin/v1/processor/*.java")
set(_proc_classes "${CMAKE_BINARY_DIR}/proc_classes")
file(MAKE_DIRECTORY "${_proc_classes}")
if(_proc_sources)
  file(WRITE "${CMAKE_BINARY_DIR}/proc_sources.txt" "")
  foreach(_src IN LISTS _proc_sources)
    file(APPEND "${CMAKE_BINARY_DIR}/proc_sources.txt" "${_src}\n")
  endforeach()
  execute_process(COMMAND "${JAVAC}" --release 25 -d "${_proc_classes}" "@${CMAKE_BINARY_DIR}/proc_sources.txt" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "Java processor javac failed: ${_out} ${_err}")
  endif()
endif()
# 2) compile SDK (without processor) + example with processor
file(GLOB_RECURSE _java_sdk_sources "${JAVA_SDK}/src/main/java/*.java")
list(FILTER _java_sdk_sources EXCLUDE REGEX ".*GeneratedTargets\\.java")
list(FILTER _java_sdk_sources EXCLUDE REGEX ".*processor/.*")
set(_java_example_src "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/java/src/main/java/org/orcaslicer/plugin/v1/examples/ExamplePlugin.java")
set(_java_sources ${_java_sdk_sources} ${_java_example_src})
set(_java_sources_file "${CMAKE_BINARY_DIR}/java_sources.txt")
file(WRITE "${_java_sources_file}" "")
foreach(_src IN LISTS _java_sources)
  file(APPEND "${_java_sources_file}" "${_src}\n")
endforeach()
set(_manifest_gz "${CMAKE_BINARY_DIR}/generated/hook-sdkgen/manifest/orca-hooks.json.gz")
if(NOT EXISTS "${_manifest_gz}")
  set(_manifest_gz "${CMAKE_BINARY_DIR}/generated/hook-sdkgen/manifest/orca-hooks.json")
endif()
execute_process(COMMAND "${JAVAC}" --release 25 -d "${JAVA_BUILD_DIR}/classes" -cp "${_proc_classes}" -processor org.orcaslicer.plugin.v1.processor.HookProcessor -processorpath "${_proc_classes}" -s "${JAVA_GEN_DIR}" -Aorca.manifest=${_manifest_gz} -Aorca.buildId=${BUILD_ID} "@${_java_sources_file}" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _res EQUAL 0)
  message(FATAL_ERROR "Java javac failed: ${_out} ${_err}")
endif()
# 3) compile generated sources (registry) if any
file(GLOB_RECURSE _gen_sources "${JAVA_GEN_DIR}/*.java")
if(_gen_sources)
  file(WRITE "${CMAKE_BINARY_DIR}/java_gen_sources.txt" "")
  foreach(_src IN LISTS _gen_sources)
    file(APPEND "${CMAKE_BINARY_DIR}/java_gen_sources.txt" "${_src}\n")
  endforeach()
  execute_process(COMMAND "${JAVAC}" --release 25 -d "${JAVA_BUILD_DIR}/classes" -cp "${JAVA_BUILD_DIR}/classes;${_proc_classes}" "@${CMAKE_BINARY_DIR}/java_gen_sources.txt" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _res EQUAL 0)
    message(FATAL_ERROR "Java gen javac failed: ${_out} ${_err}")
  endif()
endif()
file(COPY "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/java/src/main/resources/META-INF/orca/plugin.json" DESTINATION "${JAVA_BUILD_DIR}/classes/META-INF/orca")
file(READ "${JAVA_BUILD_DIR}/classes/META-INF/orca/plugin.json" _plug_json)
string(REGEX REPLACE "windows-x86_64-[a-z0-9\\-]+" "${BUILD_ID}" _plug_json_fixed "${_plug_json}")
file(WRITE "${JAVA_BUILD_DIR}/classes/META-INF/orca/plugin.json" "${_plug_json_fixed}")
execute_process(COMMAND "${JAR}" cf "${JAVA_BUILD_DIR}/libs/orca-java-example.jar" -C "${JAVA_BUILD_DIR}/classes" . RESULT_VARIABLE _res)
if(NOT _res EQUAL 0)
  message(FATAL_ERROR "Java jar failed")
endif()
message(STATUS "Java example built: ${JAVA_BUILD_DIR}/libs/orca-java-example.jar")

# Build Kotlin example (javac for SDK java + kotlinc for kotlin)
message(STATUS "Building Kotlin example...")
set(KOTLINC "C:/Users/User/.gradle/caches/9.6.1/transforms/7249690631937fb48e98932975a392fa/transformed/idea-2026.1.3-win/plugins/Kotlin/kotlinc/bin/kotlinc.bat")
if(NOT EXISTS "${KOTLINC}")
  file(GLOB _kotlinc_candidates "C:/Users/User/.gradle/caches/*/transforms/*/transformed/*/plugins/Kotlin/kotlinc/bin/kotlinc.bat")
  list(GET _kotlinc_candidates 0 KOTLINC)
endif()
set(KOTLIN_BUILD_DIR "${CMAKE_BINARY_DIR}/hook-examples/kotlin")
file(MAKE_DIRECTORY "${KOTLIN_BUILD_DIR}/classes")
file(MAKE_DIRECTORY "${KOTLIN_BUILD_DIR}/libs")
file(GLOB_RECURSE _kotlin_java_sources "${JAVA_SDK}/src/main/java/*.java")
list(FILTER _kotlin_java_sources EXCLUDE REGEX ".*GeneratedTargets\\.java")
set(_kotlin_java_sources_file "${CMAKE_BINARY_DIR}/kotlin_java_sources.txt")
file(WRITE "${_kotlin_java_sources_file}" "")
foreach(_src IN LISTS _kotlin_java_sources)
  file(APPEND "${_kotlin_java_sources_file}" "${_src}\n")
endforeach()
execute_process(COMMAND "${JAVAC}" --release 25 -d "${KOTLIN_BUILD_DIR}/classes" "@${_kotlin_java_sources_file}" RESULT_VARIABLE _res)
if(NOT _res EQUAL 0)
  message(FATAL_ERROR "Kotlin javac failed")
endif()
file(GLOB_RECURSE _sdk_kotlin_sources "${JAVA_SDK}/src/main/kotlin/*.kt")
file(GLOB_RECURSE _kotlin_example_sources "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/kotlin/src/main/kotlin/*.kt")
set(_kotlin_sources ${_sdk_kotlin_sources} ${_kotlin_example_sources})
set(_kotlin_sources_file "${CMAKE_BINARY_DIR}/kotlin_sources.txt")
file(WRITE "${_kotlin_sources_file}" "")
foreach(_src IN LISTS _kotlin_sources)
  file(APPEND "${_kotlin_sources_file}" "${_src}\n")
endforeach()
execute_process(COMMAND "${KOTLINC}" -jvm-target 25 -d "${KOTLIN_BUILD_DIR}/classes" -classpath "${KOTLIN_BUILD_DIR}/classes" "@${_kotlin_sources_file}" RESULT_VARIABLE _res OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _res EQUAL 0)
  message(FATAL_ERROR "Kotlin kotlinc failed: ${_out} ${_err}")
endif()
file(COPY "${CMAKE_SOURCE_DIR}/sdk/plugin_v1/examples/kotlin/src/main/resources/META-INF/orca/plugin.json" DESTINATION "${KOTLIN_BUILD_DIR}/classes/META-INF/orca")
file(READ "${KOTLIN_BUILD_DIR}/classes/META-INF/orca/plugin.json" _kplug_json)
string(REGEX REPLACE "windows-x86_64-[a-z0-9\\-]+" "${BUILD_ID}" _kplug_json_fixed "${_kplug_json}")
file(WRITE "${KOTLIN_BUILD_DIR}/classes/META-INF/orca/plugin.json" "${_kplug_json_fixed}")
execute_process(COMMAND "${JAR}" cf "${KOTLIN_BUILD_DIR}/libs/orca-kotlin-example.jar" -C "${KOTLIN_BUILD_DIR}/classes" . RESULT_VARIABLE _res)
if(NOT _res EQUAL 0)
  message(FATAL_ERROR "Kotlin jar failed")
endif()
# Fat jar: embed kotlin-stdlib for runtime (required for DemoLog etc.)
get_filename_component(_kotlinc_bin "${KOTLINC}" DIRECTORY)
get_filename_component(_kotlinc_home "${_kotlinc_bin}" DIRECTORY)
set(_stdlib_jar "${_kotlinc_home}/lib/kotlin-stdlib.jar")
if(EXISTS "${_stdlib_jar}")
  file(MAKE_DIRECTORY "${KOTLIN_BUILD_DIR}/stdlib_tmp")
  execute_process(COMMAND ${CMAKE_COMMAND} -E tar x "${_stdlib_jar}" WORKING_DIRECTORY "${KOTLIN_BUILD_DIR}/stdlib_tmp" RESULT_VARIABLE _tar_res ERROR_QUIET)
  if(NOT _tar_res EQUAL 0)
    execute_process(COMMAND powershell -Command "Expand-Archive -Path '${_stdlib_jar}' -DestinationPath '${KOTLIN_BUILD_DIR}/stdlib_tmp' -Force" RESULT_VARIABLE _ps_res ERROR_QUIET)
  endif()
  execute_process(COMMAND "${JAR}" uf "${KOTLIN_BUILD_DIR}/libs/orca-kotlin-example.jar" -C "${KOTLIN_BUILD_DIR}/stdlib_tmp" . RESULT_VARIABLE _uf_res ERROR_QUIET)
  file(REMOVE_RECURSE "${KOTLIN_BUILD_DIR}/stdlib_tmp")
endif()
message(STATUS "Kotlin example built: ${KOTLIN_BUILD_DIR}/libs/orca-kotlin-example.jar")

message(STATUS "All hook examples built for ${BUILD_ID}")
