#include "orca/patch2plugin/emitter.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cctype>
#include <map>

namespace fs = std::filesystem;
namespace orca::patch2plugin {

std::string sanitize_symbol(const std::string& s){
    std::string out; out.reserve(s.size());
    for(char c: s){ if(std::isalnum((unsigned char)c) || c=='_') out.push_back(c); else out.push_back('_'); }
    if(!out.empty() && std::isdigit((unsigned char)out[0])) out="_"+out;
    if(out.empty()) out="_";
    return out;
}
std::string json_escape2(const std::string& s){ return json_escape(s); }

static void write_file_deterministic(const fs::path& p, const std::string& content){
    fs::create_directories(p.parent_path());
    std::ofstream out(p, std::ios::binary);
    if(!out) throw std::runtime_error("cannot write " + p.string());
    out.write(content.data(), content.size());
    if(!out) throw std::runtime_error("write failed " + p.string());
}

void emit_plugin_project(
    const std::string& out_dir,
    const std::string& plugin_id,
    const std::string& version,
    const std::string& plugin_name,
    const ManifestInfo& manifest,
    const std::vector<ConvertedFunc>& converted,
    const std::map<std::string, std::string>& file_contents_post)
{
    // Ensure deterministic ordering
    std::vector<ConvertedFunc> sorted = converted;
    std::sort(sorted.begin(), sorted.end(), [](const ConvertedFunc& a, const ConvertedFunc& b){
        if(a.file != b.file) return a.file < b.file;
        if(a.line != b.line) return a.line < b.line;
        return a.symbol_id < b.symbol_id;
    });

    fs::path out(out_dir);
    fs::create_directories(out);
    fs::create_directories(out / "src");

    // Must not embed absolute paths
    {
        std::ostringstream oss;
        oss << "cmake_minimum_required(VERSION 3.20)\n";
        oss << "project(" << sanitize_symbol(plugin_id) << " CXX)\n";
        oss << "set(CMAKE_CXX_STANDARD 17)\n";
        oss << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
        oss << "find_package(OrcaHook REQUIRED)\n";
        oss << "add_library(${PROJECT_NAME} SHARED\n";
        oss << "    src/generated_hooks.cpp\n";
        oss << "    src/plugin_metadata.rc\n";
        oss << ")\n";
        oss << "# Add SDK plugin entry (provides register_hook)\n";
        oss << "get_filename_component(_orca_sdk_root \"${OrcaHook_DIR}/../../..\" ABSOLUTE)\n";
        oss << "if(EXISTS \"${_orca_sdk_root}/src/plugin_entry.cpp\")\n";
        oss << "    target_sources(${PROJECT_NAME} PRIVATE \"${_orca_sdk_root}/src/plugin_entry.cpp\")\n";
        oss << "endif()\n";
        oss << "target_include_directories(${PROJECT_NAME} PRIVATE\n";
        oss << "    ${OrcaHook_INCLUDE_DIRS}\n";
        oss << "    ${CMAKE_CURRENT_SOURCE_DIR}/include\n";
        oss << ")\n";
        oss << "target_link_libraries(${PROJECT_NAME} PRIVATE OrcaHook::OrcaHook)\n";
        oss << "set_target_properties(${PROJECT_NAME} PROPERTIES\n";
        oss << "    OUTPUT_NAME \"" << plugin_id << "\"\n";
        oss << "    WINDOWS_EXPORT_ALL_SYMBOLS OFF\n";
        oss << ")\n";
        std::string cmake = oss.str();
        write_file_deterministic(out / "CMakeLists.txt", cmake);
    }

    {
        std::ostringstream oss;
        oss << "#include \"orca/plugin/plugin.hpp\"\n";
        oss << "#include \"orca/plugin/hook.hpp\"\n";
        oss << "#include \"orca/plugin/detail/registry.hpp\"\n";
        oss << "#if __has_include(\"orca_hook_api.h\")\n";
        oss << "#include \"orca_hook_api.h\"\n";
        oss << "#elif __has_include(\"abi/orca_hook_api.h\")\n";
        oss << "#include \"abi/orca_hook_api.h\"\n";
        oss << "#endif\n";
        oss << "#include <cstdint>\n";
        oss << "#include <string>\n";
        oss << "\n";
        oss << "// Generated by patch2plugin - build_id: " << manifest.build_id << "\n";
        oss << "// Converted functions: " << sorted.size() << "\n";
        for(auto &cf: sorted){
            oss << "// - " << cf.qualified << " (" << cf.file << ":" << cf.line << ") -> " << cf.symbol_id << " rva " << cf.rva << "\n";
        }
        oss << "\n";
        oss << "\n";
        // Emit renamed functions inside namespace but guarded to avoid needing original includes
        // The body is included for verification but not compiled (requires original headers which are not part of SDK)
        oss << "namespace patch2plugin_generated {\n";
        oss << "#if 0 // patched bodies - not compiled, only for verification\n";
        for(auto &cf: sorted){
            std::string san = sanitize_symbol(cf.symbol_id);
            std::string func_text = cf.full_text;
            std::string renamed = "patch2plugin_" + san;
            size_t pos = func_text.find(cf.qualified);
            if(pos != std::string::npos){
                func_text.replace(pos, cf.qualified.size(), renamed);
            } else {
                pos = func_text.find(cf.func_name);
                if(pos != std::string::npos){
                    func_text.replace(pos, cf.func_name.size(), renamed);
                }
            }
            oss << "\n// Patched function for symbol " << cf.symbol_id << " rva " << cf.rva << "\n";
            oss << func_text << "\n";
        }
        oss << "#endif // patched bodies\n";
        oss << "} // namespace patch2plugin_generated\n\n";
        for(auto &cf: sorted){
            std::string san = sanitize_symbol(cf.symbol_id);
            oss << "inline constexpr ::orca::plugin::HookTarget<void(*)()> kTarget_" << san << "{\"" << cf.symbol_id << "\", " << cf.rva << "};\n";
            oss << "orca_hook_status_t hook_replace_" << san << "(orca_cpu_context_t* ctx, orca_hook_result_t* out, orca_hook_status_t (*next)(orca_cpu_context_t*) noexcept, void* user_data) noexcept {\n";
            oss << "    (void)user_data;\n";
            oss << "    if (next) next(ctx);\n";
            oss << "    if (out) { out->size = sizeof(*out); out->version = ORCA_HOOK_ABI_VERSION; out->action = ORCA_HOOK_ACTION_CONTINUE; }\n";
            oss << "    return ORCA_HOOK_OK;\n";
            oss << "}\n";
            oss << "ORCA_REPLACE_PRIO(kTarget_" << san << ", hook_replace_" << san << ", 1000)\n\n";
        }
        write_file_deterministic(out / "src" / "generated_hooks.cpp", oss.str());
    }

    {
        std::ostringstream json;
        json << "{\"schema\":1";
        json << ",\"id\":\"" << json_escape2(plugin_id) << "\"";
        std::string name = plugin_name.empty() ? plugin_id : plugin_name;
        json << ",\"name\":\"" << json_escape2(name) << "\"";
        json << ",\"version\":\"" << json_escape2(version) << "\"";
        json << ",\"runtime\":\"native\"";
        json << ",\"language\":\"cpp\"";
        json << ",\"hook_abi\":1";
        json << ",\"targets\":[{\"os\":\"" << json_escape2(manifest.os.empty() ? "windows" : manifest.os) << "\",\"arch\":\"" << json_escape2(manifest.arch.empty() ? "x86_64" : manifest.arch) << "\",\"build_id\":\"" << json_escape2(manifest.build_id) << "\"}]";
        json << "}";
        std::string json_str = json.str();
        std::string rc_escaped;
        for(char c: json_str){
            if(c=='"') rc_escaped += "\"\"";
            else rc_escaped.push_back(c);
        }
        std::ostringstream rc;
        rc << "1 \"ORCA_PLUGIN_METADATA\"\n";
        rc << "BEGIN\n";
        rc << "    \"" << rc_escaped << "\\0\"\n";
        rc << "END\n";
        write_file_deterministic(out / "src" / "plugin_metadata.rc", rc.str());
    }

    {
        std::ostringstream oss;
        oss << "# " << (plugin_name.empty()?plugin_id:plugin_name) << "\n\n";
        oss << "Generated by patch2plugin from patch.\n\n";
        oss << "## Build\n\n";
        oss << "```bat\n";
        oss << "cmake -S . -B build -G Ninja ^\n";
        oss << "  -DCMAKE_PREFIX_PATH=\"<path-to-generated-plugin-sdk/" << manifest.build_id << "/cpp>\" ^\n";
        oss << "  -DCMAKE_C_COMPILER=\"clang-cl\" -DCMAKE_CXX_COMPILER=\"clang-cl\"\n";
        oss << "cmake --build build --config RelWithDebInfo\n";
        oss << "```\n\n";
        oss << "Or using Orca build tree:\n";
        oss << "```bat\n";
        oss << "cmake --build cmake-build-relwithdebinfo-visual-studio-llvm --target OrcaSlicer\n";
        oss << "```\n\n";
        oss << "## Converted functions\n\n";
        if(sorted.empty()){
            oss << "_none_\n";
        } else {
            for(auto &cf: sorted){
                oss << "- `" << cf.qualified << "` in `" << cf.file << ":" << cf.line << "` -> `" << cf.symbol_id << "` rva " << cf.rva << "\n";
            }
        }
        oss << "\n";
        oss << "Plugin id: `" << plugin_id << "` version: `" << version << "` build_id: `" << manifest.build_id << "`\n";
        write_file_deterministic(out / "README.md", oss.str());
    }
} // emit_plugin_project
} // namespace orca::patch2plugin
